# Practical Questions

# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed array:")
print(transposed_array)


Original array:
[[13 39 92]
 [12  2 57]
 [53 13 11]]

Transposed array:
[[13 12 53]
 [39  2 13]
 [92 57 11]]


# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array = np.arange(10)

# Print the original array
print("Original 1D array:")
print(array)

# Reshape the array into a 2x5 array
reshaped_2x5 = array.reshape(2, 5)
print("\nReshaped to 2x5 array:")
print(reshaped_2x5)

# Reshape the array into a 5x2 array
reshaped_5x2 = array.reshape(5, 2)
print("\nReshaped to 5x2 array:")
print(reshaped_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [3]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.random((4, 4))

# Print the original array
print("Original 4x4 array:")
print(array)

# Add a border of zeros around the array
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 array with border of zeros:")
print(bordered_array)


Original 4x4 array:
[[0.2037417  0.30884895 0.81307318 0.74700227]
 [0.0256777  0.915862   0.63749283 0.16803073]
 [0.5261983  0.90554842 0.84056044 0.6995385 ]
 [0.23223469 0.71138363 0.98131261 0.16951231]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.2037417  0.30884895 0.81307318 0.74700227 0.        ]
 [0.         0.0256777  0.915862   0.63749283 0.16803073 0.        ]
 [0.         0.5261983  0.90554842 0.84056044 0.6995385  0.        ]
 [0.         0.23223469 0.71138363 0.98131261 0.16951231 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]




# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.



In [8]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]



# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.



In [9]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

# Print the original array and the transformed arrays
print("Original array:")
print(array)

print("\nUppercase transformation:")
print(uppercase_array)

print("\nLowercase transformation:")
print(lowercase_array)

print("\nTitle case transformation:")
print(titlecase_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase transformation:
['python' 'numpy' 'pandas']

Title case transformation:
['Python' 'Numpy' 'Pandas']



# Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.



In [10]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Print the original array and the transformed array
print("Original array:")
print(words_array)

print("\nArray with spaces between characters:")
print(spaced_words_array)


Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']



# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.



In [11]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
# Add a small constant to avoid division by zero if necessary
division = array1 / (array2 + 1e-10)

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]



# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.



In [12]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]



# Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.



In [13]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)

# Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in array if is_prime(num)]

# Print the array and the prime numbers found
print("Array of random integers:")
print(array)

print("\nPrime numbers in the array:")
print(prime_numbers)


Array of random integers:
[642 815 477 204 499 936 761 107 437 248 142 344 156 103 950  46 629 669
 638 575 438 971 920 869 972 439  48 381 953 106 694 373  62 123 764 308
 694 212 607 379 512 839 108 712 888 599 504 912 298 808 543 665 550 226
 429 185 206 212 590 990 515 141 900 677 290 140 804 887 316 411 806 100
 917  67 384 359 672 249 988 568 485 244 633 538 841 756 442  87 925 831
 155 420 652 756 207 981 821 970 984  60]

Prime numbers in the array:
[499, 761, 107, 103, 971, 439, 953, 373, 607, 379, 839, 599, 677, 887, 67, 359, 821]



# Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


In [15]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Here we use random temperatures between -10 and 35 degrees Celsius
daily_temperatures = np.random.randint(-10, 36, size=30)

# Reshape the array into a 2D array where each row represents a week
# Assuming 5 weeks of 6 days each
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the daily temperatures and weekly averages
print("Daily temperatures for the month:")
print(daily_temperatures)

print("\nWeekly temperatures:")
print(weekly_temperatures)

print("\nWeekly averages:")
print(weekly_averages)


Daily temperatures for the month:
[ 15  30  12 -10   5  30  32   6  19  15  32  10  -3   5  29  -3  23   4
   5  -8   4   5  -1  31   7   9  31  26  -8  34]

Weekly temperatures:
[[ 15  30  12 -10   5  30]
 [ 32   6  19  15  32  10]
 [ -3   5  29  -3  23   4]
 [  5  -8   4   5  -1  31]
 [  7   9  31  26  -8  34]]

Weekly averages:
[13.66666667 19.          9.16666667  6.         16.5       ]
